---
- hosts: appdbs
  roles:
    - role: geerlingguy.postgresql
      become: yes

  handlers:
    - name: restart postgres
      service:
        name: postgresql
        state: restarted

# - name: deploy postgres
#   hosts: apps
#   gather_facts: false
#   become: true
#   hosts: appdbs
#   tasks:
#   - name: install progress
#     command: "yum install -y postgresql-server"

#   #- name: install postgres
#   #  yum:
#   #    name: postgresql-server
#   #    state: latest
#   - name: enable postgres at boot
#     service:
#       name: postgresql
#       enabled: yes
#   - name: tell user to finish setting up postgres
#     debug:
#       msg: "Either uncomment the postgres setup or manually login and initialize"

#  # only run the next 2 tasks once!
# #  - name: initilize postgres
# #    command: postgresql-setup initdb
# #  - name: initilize postgres some more
# #    command: chkconfig postgresql on
#   - name: start postgres
#     service:
#       name: postgresql.service
#       state: started

